# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonnacci_list(limit):
    if limit <= 1:
        return [,]
    elif limit == 2:
        return [1,]
    else: # limit > 2
        f_list = [1, 2]
        next_num = 0
        while next_num < limit:
            next_num = f_list[-1] + f_list [-2]
            if next_num < limit:
                f_list.append(next_num)
        return f_list

if __name__ == '__main__':
    fib_sum = 0
    for n in fibonnacci_list(4000000):
        if n % 2 == 00:
            fib_sum += n
    print (fib_sum)
